### PR TITLE
User interface game - Milestone 2

### PR DESCRIPTION
**Pull request by saimaAnis21**
In this branch I have designed the user interface which prompts the user and takes their inputs.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required

## Hello team 👋.

**Great job on your project 💪. It does show you have an understanding of the game flow. There are however a few requirements needed before the project can be approved.**

1). **Display the message that the user gets when they select an invalid move.**
2). **Use a game board to show how the game looks after a move is played.**
3).**Use a game board to show how a winning move looks like.**
4)**Use a game board to show how a draw move looks like.**
5). **The while loop defined on line 40 of your `main.rb` file should not be a commented out. It is part of the game flow since it enwraps all the games' repeated actions.**

## Happy coding 🥂.

**PS: You can reach me on slack(Rose Wanjohi).**

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Status: Changes Required
Hello team,
Great work on the project so far, all your efforts are visible from the changes made but we have to make a few more changes to get this milestone Approved. Let me break down the changes for you.
[REQUIRED] 
- [x] Game informs player if the selected move is invalid 
- [x] The last player move should not be removed from the board after each round.
- [x] Game informs player if the selected move is a winning move.
- [x] Game informs player if the selected move is a draw move.

Keep up with the efforts towards this project, you are almost there.
Cheers!!
Rindra Josia

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @saimaAnis21   ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [ ] The game should register when it is a winning move, it currently just moves on in the game asking the next player to pick a number.
 
**See here** 👇 

image

- [x] When the game ends on a draw, it asks the players if they'll like to play again, but then it starts on the already filled up space of the game board. Please fix it, so it starts on an empty board.
**Optional**
- [x] Game asks players for their names

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by teekaytech — APPROVED** [review]
# Status: Approved :green_circle: 

### Congratulations team, this milestone has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:


You can now merge to the development branch.
Good luck with your next milestone.

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Pull request merged**
